networks:
    mg_transform:
        driver: bridge

services:
    transform:
        container_name: mg_transform
        image: molgenis/molgenis-py-lifelines-transform:latest
        volumes:
            - ../catalog:/usr/src/app/catalog
            - ../generated:/usr/src/app/generated
            - ../config.json:/usr/src/app/config.json
        networks:
            - mg_transform
        depends_on:
            - molgenis

    nginx:
        environment:
            MOLGENIS_HOST: ${MOLGENIS_HOST:-host.docker.internal}
        container_name: mg_nginx
        image: nginx
        networks:
            - mg_transform
        ports:
            - 80:80
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/localhost.tpl:/tmp/localhost.tpl
            - ../:/usr/share/nginx/html
        command: >
            /bin/bash -c "envsubst \"`for v in $$(compgen -v);do printf '$${%s} ' $$v;done`'\"
            < /tmp/localhost.tpl
            > /etc/nginx/localhost
            && nginx -g 'daemon off;'"

    molgenis:
        container_name: mg_molgenis
        depends_on:
            - elasticsearch
            - minio
            - postgresql
            - nginx
        environment:
            - molgenis.home=/home/molgenis
            - elasticsearch.transport.addresses=elasticsearch:9300
            - db_uri=jdbc:postgresql://postgresql/molgenis
            - db_user=molgenis
            - db_password=molgenis
            - admin.password=admin
            - MINIO_BUCKET_NAME=molgenis
            - MINIO_ENDPOINT=http://minio:9000
            - MINIO_ACCESS_KEY=molgenis
            - MINIO_SECRET_KEY=molgenis
            - "CATALINA_OPTS=-Xmx2g -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled"
        image: registry.molgenis.org/molgenis/molgenis-app:dev
        networks:
            - mg_transform
        ports:
            - 8080:8080

    postgresql:
        container_name: mg_postgresql
        environment:
            - POSTGRES_DB=molgenis
            - POSTGRES_USER=molgenis
            - POSTGRES_PASSWORD=molgenis
        image: postgres:11-alpine
        networks:
            - mg_transform
        ports:
            - 5432:5432
        volumes:
            - ./init_db.sql:/docker-entrypoint-initdb.d/init.sql
            - postgresql:/var/lib/postgresql/data

    elasticsearch:
        container_name: mg_elasticsearch
        environment:
            - cluster.name=molgenis
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - xpack.security.enabled=false
            - xpack.monitoring.enabled=false
            - xpack.watcher.enabled=false
            - discovery.type=single-node
        image: docker.elastic.co/elasticsearch/elasticsearch:5.5.3
        networks:
            - mg_transform
        ports:
            - 9200:9200
            - 9300:9300
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - elasticsearch:/usr/share/elasticsearch/data

    minio:
        container_name: mg_minio
        command: server /data
        environment:
            MINIO_ACCESS_KEY: molgenis
            MINIO_SECRET_KEY: molgenis
        image: minio/minio:RELEASE.2019-03-20T22-38-47Z
        networks:
            - mg_transform
        ports:
            - 9000:9000
        volumes:
            - minio:/data

version: "3.8"
volumes:
    elasticsearch:
    minio:
    postgresql:
